def get_rnn_words():
    return [['well', 'one', 'time', 'rarely', "'s", 'however', 'journey', 'affects', '.'],
            ['grim',
             'unflinchingly',
             'well',
             'unflinchingly',
             'unflinchingly',
             'unflinchingly',
             'unflinchingly',
             'unflinchingly',
             'unflinchingly'],
            ['filmmaker',
             'never',
             'nolan',
             'whether',
             'major',
             'still',
             'another',
             'another',
             'even'],
            ['one', 'locales', 'however', '.', '.', '.', 'time', ',', 'still'],
            ['slow', 'good', ',', 'slow', '_', 'made', 'also', "'s", '!good!'],
            ['men',
             'refreshingly',
             'time',
             '.',
             'another',
             'time',
             'whimsical',
             'another',
             'touches',
             'many'],
            ['laborious', 'films', 'another', 'though', '!rarely!'],
            ['well',
             'either',
             'earlier',
             "'s",
             ',',
             'since',
             'lot',
             'your',
             'tax',
             'fiancée'],
            ['of', ',', 'much', "'s", 'wanted', 'really', 'even'],
            ['sinking',
             'utter',
             'from',
             'jerky',
             'of',
             'turkey',
             'igloo',
             'sitting',
             'time',
             'formula'],
            ['part',
             'letting',
             'of',
             'first',
             'leads',
             'movie',
             'audiences',
             'put',
             'even',
             'time'],
            ['forster', 'one', 'meara', 'laziness', 'well', 'still', 'levy', 'many'],
            ['of', 'another', 'time', 'thing', 'balance', 'part', 'enough'],
            ['!help!'],
            ['!.!'],
            ['blend',
             'from',
             'dancing',
             'made',
             'well',
             'one',
             '.',
             'music',
             'also',
             'also'],
            ['strikes',
             'continue',
             'never',
             'nobody',
             "'s",
             'nerve',
             'even',
             'well',
             'still'],
            ['since',
             'well',
             'amélie',
             'picking',
             'wife',
             'since',
             'never',
             'even',
             'also'],
            ['monster',
             ',',
             'think',
             'nothing',
             'old',
             'plain',
             'one',
             'film',
             'first',
             'one'],
            ['low',
             'since',
             'resembling',
             'its',
             'production',
             'elementary',
             'of',
             'also'],
            ['!goes!'],
            ['lasts', '-', 'iditarod', ',', 'time', 'day', 'well', 'asked', "n't"],
            ['.', 'caulfield', ',', 'holden', '!make!'],
            ['one', 'thriller', 'my', 'read', ',', 'two', '.', 'filled', 'well'],
            ['of', 'one', 'well', 'time', 'spirit', 'his', 'rarely', '.', 'another'],
            ['stale', 'spoof', 'could', 'runs', 'way', 'others', 'risque'],
            ['tenuous',
             'well',
             'purport',
             'time',
             'emotional',
             '102-year',
             'connections',
             'another',
             'action',
             'materials'],
            ['at',
             'taking',
             'part',
             'even',
             'party',
             'whose',
             'made',
             'could',
             'yet',
             "'s"],
            ['cut-and-paste',
             'job',
             'cookie-cutter',
             "'s",
             'well',
             'one',
             '.',
             'another',
             'although',
             'movies'],
            [',', 'even', '-', 'well', 'really', 'made', 'became', 'help'],
            ['women',
             'less',
             'subsidiary',
             'variation',
             'niece',
             'scott',
             "'s",
             "'s",
             'charismatic',
             'since'],
            ['!yawns!'],
            ['.', 'witty', 'well', '.', 'another', 'alluring', 'hollywood', 'one', 'one'],
            ['could', '!draw!'],
            [',', 'since', "n't", 'nothing', 'sort', "'s", "n't", 'also', 'yet'],
            ['sequences', '-', 'one', 'scenes', "'em", 'away', 'of', 'well'],
            ['sure',
             'of',
             'unerring',
             'time',
             'professionalism',
             'embedded',
             'another',
             'another',
             'since',
             'proved'],
            ['!demands!'],
            ['!visually!'],
            ['hollywood',
             'nothing',
             'adeptly',
             '.',
             'one',
             'studios',
             'well',
             'still',
             'another',
             'affects'],
            ['even', '!hardly!'],
            ['although',
             'underneath',
             'inhabitants',
             'film',
             'holy',
             'also',
             'another',
             '.',
             'lands'],
            ['touch', 'one', 'part', 'of', "''", 'elling', 'situation', 'still'],
            ['even',
             'time',
             'characters',
             'another',
             'regal',
             'well',
             'embodies',
             'holm',
             '?',
             'charisma'],
            ['cameras', 'others', 'character', 'its', '!without!'],
            ['!far!'],
            ['!synthesis!'],
            [')', 'part', 'for', '(', '.', 'less', 'time', 'one', 'another', 'chiller'],
            ['one', 'his', 'of', 'first', 'one', 'at', 'clint'],
            ['hindered', 'of', 'lead', 'plot', 'one', 'even', 'by', 'whose', 'another'],
            ['rote', 'tarted', 'after-school', 'fancy', 'also', 'gazing', 'its', 'plot'],
            ['still',
             'sensitive',
             '.',
             'anne-sophie',
             'drama',
             'exceedingly',
             'part',
             'part',
             'also',
             'among'],
            ['!even!'],
            ['one', 'atheistic', 'one', 'at', "n't", 'another', 'eponymous', 'one'],
            ['collateral', 'devoid', 'making', 'way', 'sted', 'one', 'stories'],
            ['family', 'one', 'even', 'also', 'drama', 'tender', 'one', 'one', 'one'],
            ['something', 'misanthropic', 'never', 'could', '!quite!'],
            ['definitely', 'cold', 'turkey', 'part', 'one', 'yet', ',', 'also', 'titles'],
            ['!also!'],
            ['superficial', '!also!'],
            ['even',
             'whose',
             'made',
             'still',
             'of',
             'want',
             'misfits',
             'together',
             '.',
             'stand'],
            ['films',
             'persistently',
             'hang',
             'schaeffer',
             'resuscitation',
             'would',
             'looking',
             'his',
             'hook'],
            ['!could!'],
            ['move',
             'tricky',
             'discussion',
             ',',
             'one',
             'on',
             'its',
             'also',
             'right',
             '.'],
            ['!since!'],
            ['!film!'],
            ['!right!'],
            ['hollywood', '.', '.', 'highly', 'one', 'even', 'fast', 'one'],
            ['old-fashioned', '!left!'],
            ['fanatics', ',', '!hollywood!'],
            ['!lily!'],
            ['berling',
             'veteran',
             'profoundly',
             'made',
             'chamber',
             'still',
             'bouquet',
             'since',
             'time',
             'tics'],
            ['evoke', 'poignance', '!low!'],
            ['people', 'across', 'rivaling', 'time', '.', 'either', '.', '!could!'],
            ['however',
             'string',
             'since',
             'one',
             'vulgarity',
             'of',
             'sight',
             'based',
             'rehashed'],
            ['!less!'],
            ['away', 'sum', 'its', 'time', 'live', 'first', 'movies', 'of', 'parts'],
            ['moment',
             'of',
             'its',
             'even',
             'made',
             'earns',
             "'s",
             'one',
             'another',
             'wife'],
            ['also',
             'must',
             'time',
             'however',
             'whose',
             'expected',
             '.',
             'documentary',
             'one'],
            ['stupefying',
             'by',
             'of',
             'trains',
             'bangs',
             'toilet',
             'one',
             'could',
             'movie'],
            ['by', 'performance', ',', '?', 'for', 'one', 'huge', "''", 'draw', 'howard'],
            ['hang', 'last', 'red', '!able!'],
            ['revolve', 'even', 'made', "'s", 'enough', 'around', '!treatments!'],
            ['!could!'],
            ['since', '(', 'include', 'however', '.', 'first', 'hippies', "'s", 'for'],
            ['hidden',
             'another',
             'showed',
             'one',
             ')',
             'various',
             'time',
             'by',
             'hollywood',
             'quills'],
            ['trifle', 'flat', 'make', 'still', ',', 'time', 'line', '.'],
            ['!character!'],
            ['things', 'wanted', 'turned', 'subconscious', "!n't!"],
            ['!even!'],
            ['!its!'],
            ['real', 'listeners', 'one', '.', 'least', 'enterprise', 'way'],
            ['!recognise!'],
            ['!one!'],
            ['reduces',
             'probably',
             'later',
             'time',
             'yet',
             'also',
             'melodrama',
             'byler',
             '.',
             'try'],
            ['!captivating!'],
            ['vital', 'underarm', 'able', 'yet', "'s", 'script', 'process', 'one'],
            ['sleight',
             'one',
             'one',
             'possible',
             'oscar',
             'whose',
             'director',
             'downturn'],
            ['wit', 'banality', 'for', 'on', 'another', 'also', '!one!'],
            ['marginal', 'historical', 'much', '!certain!'],
            ['could',
             'one',
             'also',
             'neither',
             '.',
             'donovan',
             'formula',
             'offbeat',
             'lead',
             "!n't!"],
            ['!poetically!'],
            ['photographs',
             'also',
             'keeps',
             'distance',
             'without',
             'character',
             'from',
             'time',
             'anything',
             'memorable'],
            ['also',
             'one',
             "n't",
             'performances',
             'understated',
             'many',
             'also',
             'still',
             'another'],
            ['one', 'one', 'potential', 'grandmother', 'still', 'try'],
            ['heavy',
             'metal',
             'also',
             'lot',
             'another',
             'combining',
             'blared',
             'editing',
             'under',
             'one'],
            ['cast', 'two', 'first', '.', 'morals', "'s", 'another', 'movies'],
            ["n't", "n't", 'kilmer', 'would', 'val', 'three', 'one', 'personas'],
            ['repugnance',
             'left',
             'much',
             'time',
             'wincing',
             'must',
             'go',
             'still',
             'one'],
            ['one', 'time', 'would', 'one', 'later', "'ve", 'one', 'must', 'last', "'s"],
            ['originality', 'wit', 'also', 'scores', 'either', '.', 'however', 'points'],
            ['appealing', 'presence', 'even', 'least', '!everyone!'],
            ['!one!'],
            ['part', 'film', ',', 'one', '.', '.', '.', '.', '.'],
            ['never',
             'also',
             'made',
             'say',
             'make',
             'least',
             'also',
             'its',
             'however',
             "n't"],
            ['!,!'],
            ['even', '!gives!'],
            ['style',
             'less',
             'its',
             'unforced',
             '.',
             'character',
             '.',
             'saying',
             'time',
             'one'],
            ['!one!'],
            ['of', 'treads', 'able', 'goes', 'nothing', 'time', 'close', 'bike'],
            ['sexuality',
             'also',
             'japan',
             'water',
             'also',
             'time',
             'men',
             'connections',
             'although',
             'also'],
            ["!'ll!"],
            ['its', 'moviemaking', 'at'],
            ['!formula!'],
            ['!faces!'],
            ['one',
             'also',
             'one',
             'even',
             'whether',
             'movies',
             'u.s.',
             '.',
             'approached'],
            ['confirms', 'made', 'cameras', 'front', 'behind', 'also', 'could', 'ethan'],
            ['two',
             'want',
             'since',
             'time',
             'back',
             'still',
             'prices',
             'first',
             'weekend'],
            ['nuanced',
             'nothing',
             'character',
             'street',
             'surrounds',
             'two',
             'narrative',
             'his'],
            ['plot', 'one', 'another', '.', 'time', 'even', 'cast', 'fears'],
            ['of', 'time', 'from', ',', 'narrative', 'comprehensible', 'one'],
            ['one', 'much', 'execution', 'space', '.', 'less', 'also'],
            ['!even!'],
            ['something',
             'scattershot',
             'could',
             'legendary',
             'of',
             'sorimachi',
             'part',
             'stylish',
             'although',
             'also'],
            ['relationships', '.', ',', 'since', "'s", 'on', 'interminably'],
            ['!dark!'],
            ['!really!'],
            ['dismissive', 'familiar', 'also', 'also', 'thoroughly', 'time'],
            ['come', '.', 'walker', 'one', 'one', 'however', 'also', 'kuras', '.'],
            ['time', 'film', 'time', 'depression-era', "'s", 'nothing', '!way!'],
            ['!of!'],
            ['could',
             'developed',
             'directed',
             'zigzag',
             'sufficiently',
             'part',
             'of',
             'characters',
             'around',
             ','],
            ['something', 'messages', 'men', 'receive', 'thyself', '!anything!'],
            ['?', 'almost', 'one', 'one', 'one', 'still', 'films', 'made', 'stir'],
            ['could',
             'lifeless',
             'directed',
             'tricks',
             'york',
             ')',
             'another',
             '(',
             'learn',
             'although'],
            ['heart', 'absolutely', '!since!'],
            ['psychological', 'much', 'whose', 'made'],
            ['!little!'],
            ['things',
             'familiar',
             'enough',
             'of',
             'really',
             'since',
             'could',
             'worked',
             'produce',
             'underground'],
            ['resonance', 'appears', 'one', 'its', 'rhythms', 'fact', 'even', 'male'],
            ['for', 'part', 'time', 'tried', 'overall', 'try', 'less', "'s", 'wo'],
            ['its', 'one', '.', 'also', '.', '.', 'one', 'swashbuckler'],
            ['repetitions',
             'following',
             'least',
             'would',
             'directed',
             'also',
             'its',
             'even',
             'one',
             'still'],
            ['absurd',
             'one',
             'movie',
             'heavy-handed',
             'part',
             'still',
             ',',
             'become',
             'consequence',
             'even'],
            ['examinations',
             'of',
             'one',
             'female',
             'solid',
             'even',
             'part',
             'midlife',
             'one'],
            ['!dates!'],
            ["n't", 'help', 'transcend', 'one', '.', 'plot', ',', 'drug'],
            ['lifeless', '!film!'],
            ["!'m!"],
            ['even', 'yet', "'s", 'also', 'leon', 'curiously', 'also', '!longer!'],
            ['!help!'],
            ['first', 'bees', '!precisely!'],
            ['also', 'stories', "n't", 'even', "'s", 'say', 'could', "'s", 'way'],
            ['one',
             'tickle',
             'theatres',
             'slapstick',
             'without',
             'others',
             'would',
             'help',
             'one',
             'on'],
            ['film',
             'ilya',
             'two',
             'chaiken',
             'by',
             'one',
             "'s",
             'even',
             'pic',
             'mother'],
            ['screens', 'look', 'for', 'also', 'for', '!debate!'],
            ['!handful!'],
            ['believe',
             "'s",
             'part',
             'one',
             "n't",
             'ending',
             'movie',
             'resulting',
             'still',
             'however'],
            ['supposed',
             'either',
             'at',
             'days',
             'even',
             '.',
             'would',
             'manages',
             'another'],
            ['!performances!'],
            ['even', "'s", 'made', '.', 'fact', '.', '.'],
            ['shimmering',
             'looking',
             'always',
             'occasionally',
             ',',
             'lymphoma',
             ',',
             'often'],
            ['!waiting!'],
            ['!extremely!'],
            ['!david!'],
            ['also', 'time', 'one', 'its', 'bleakly', 'time', 'give', 'for', 'character'],
            ['!gussied!'],
            ['offered', 'besides', 'screens', 'bawdy', ',', 'sets', 'would', 'another'],
            ['!of!'],
            ['even', 'still', 'performances', "'s", 'films', 'time', 'one', 'one', 'one'],
            ['films', "n't", 'unless', 'way', 'stupid', 'also', "'s"],
            ["n't", 'much', 'substance', 'its', 'blooper', 'although', 'become'],
            ['!issues!'],
            ['!your!'],
            ['!also!'],
            ['anybody', 'whose', 'moviemaking', 'also', 'david', '.', 'for', 'for'],
            ['even',
             'mental',
             'nothing',
             'still',
             'still',
             'existential',
             'even',
             'however',
             'would',
             '.'],
            ['first',
             'nothing',
             'another',
             'orbit',
             'one',
             'pacino',
             'la',
             'one',
             'contrivance',
             'veritable'],
            ['pieces',
             'homophobic',
             'hip',
             'young',
             'itself',
             'filth',
             'away',
             'of',
             'could',
             'one'],
            ['least', 'one', 'try', '2,000', 'still', 'also', 'u.s.', 'another', 'come'],
            ['want', "n't", '!', 'shouts', 'trying', 'one', 'ca', 'seen', 'single'],
            ['rare',
             'less',
             'would',
             'also',
             'one',
             'still',
             "'s",
             'outer',
             "'s",
             'even'],
            ['part', 'one', 'sure', 'would', 'individuals', '!one!'],
            ['even',
             'nearly',
             'nevertheless',
             'rather',
             'characters',
             'another',
             'wife',
             'languages',
             'body',
             'morvern'],
            ['unassuming',
             'life',
             'sociologically',
             "'s",
             'of',
             'pointing',
             'urban',
             'either',
             'another'],
            ['!were!'],
            ['also', 'today', 'one', 'mild', 'much', 'time', "'s", 'delhi', 'one', '.'],
            ['slim', "!'d!"],
            ['similarly',
             'on',
             'sentiments',
             'shown',
             'anything',
             'button',
             'somewhere',
             'even',
             'fact'],
            ['wanted',
             'derrida',
             'one',
             'wanted',
             'also',
             'at',
             'everyone',
             'extremely',
             'anything',
             'even'],
            ['!nothing!'],
            ['want',
             'saying',
             'your',
             'moral',
             'help',
             'plot',
             'need',
             'much',
             'still',
             'outside'],
            ['directing', '!everything!'],
            [','],
            ['must',
             "'",
             'ego',
             'doldrums',
             'one',
             'also',
             '``',
             'touching',
             'children',
             'makes'],
            ['one', 'categories', 'of', '!away!'],
            ['movie',
             'also',
             'within',
             'even',
             'another',
             'another',
             'of',
             'stays',
             'confines',
             'another'],
            ['one', 'scorchingly', '.', 'provocative', '.'],
            ['!everyone!'],
            ['audiences', 'still', 'boxing', ',', '!need!'],
            ['across',
             'also',
             'first',
             'time',
             'much',
             '.',
             'powers',
             'friend',
             'less',
             'much'],
            ['!one!'],
            ['woman', 'part', 'also', 'still', 'whole', ','],
            ['his', 'feel', 'burns', '!help!'],
            ['saddled',
             'two',
             'even',
             'also',
             'insightful',
             'without',
             'for',
             'arts',
             'york'],
            ['!prison!'],
            ['one', 'its', 'people', 'want', 'act', 'intimacy', 'even', '.', 'its'],
            ['!one!'],
            ['!originality!'],
            ['general', 'could', '!away!'],
            ['poignancy',
             '(',
             'strides',
             ',',
             'deconstructed',
             ')',
             'personal',
             'think',
             'said'],
            ['one', 'since', 'my', 'words', ';', ',', 'reactions', 'my', 'my'],
            ['debut',
             'above-average',
             'cast',
             'another',
             'directing',
             'time',
             'of',
             'paxton',
             'actress',
             'rural'],
            ['!one!'],
            ['one', 'perhaps', 'really', '!one!'],
            ['!one!'],
            [',', 'objective', 'course', 'less', 'of', 'equally', "!n't!"],
            ['made', ',', 'even', "n't", 'also', 'leads', 'still', ',', 'diggs'],
            ["!n't!"],
            ['would',
             'written',
             'hardly',
             'way',
             'hollywood',
             'use',
             'recently',
             'give',
             '.'],
            ['even',
             'watched',
             'one',
             'later',
             'making',
             'something',
             'seen',
             "n't",
             '_'],
            ['also', '_', 'character', 'performances', 'first', 'their', 'bring'],
            ['without',
             'one',
             'impish',
             'films',
             'martial',
             'art',
             'pow',
             'others',
             'fu'],
            ['!come!'],
            ['sparring',
             'still',
             'jackson',
             '.',
             'affleck',
             'partners',
             'even',
             'affleck',
             'affleck'],
            ['!of!'],
            ['even', ',', 'japan', 'year', 'specter', 'of', 'say'],
            ['time', 'cannot', 'another', 'move', 'made', '!improve!'],
            ['!limp!'],
            ['another',
             'prior',
             'one',
             'also',
             'another',
             'between',
             'of',
             'one',
             'despite',
             'examines'],
            ['even',
             'experiences',
             '2-d',
             'animation',
             'hollywood',
             'one',
             '.',
             'making',
             'another'],
            ['since', 'first', 'anything', '!taken!'],
            ['come', 'monty', 'still', 'really', 'python', 'however', 'one', 'sketch'],
            ['one',
             'songs',
             'movie',
             'away',
             'lead',
             'wo',
             'along',
             'another',
             'century',
             'another'],
            ["n't", 'able', 'last', 'dankworth', '(', '.', 'its', 'character'],
            ['even',
             'by',
             'his',
             'three',
             'artists',
             'his',
             'worked',
             'still',
             'another'],
            ['part', 'chancellor', 'wit', 'say', 'anna', ',', 'of', '`'],
            ['!halfhearted!'],
            ['!also!'],
            ['sort', 'also', 'another', 'made', 'nails', 'another', 'huston'],
            ['yet',
             'struck',
             'would',
             'child',
             'although',
             'cinemas',
             'time',
             'of',
             'even',
             "'s"],
            ['tries', 'harder', 'could', 'part', '!enough!'],
            ['power',
             'later',
             'confirms',
             "'s",
             'performance',
             'cate',
             'even',
             'turned',
             'mother',
             'cate'],
            ['!day!'],
            ['!might!'],
            ['another', 'master', 'one', 'heinous', 'able', 'least', 'must', 'first'],
            ['delivered', '!occasionally!'],
            ['blown',
             'help',
             'his',
             'even',
             'everyone',
             'album',
             'seems',
             'whole',
             'leaving',
             'last'],
            ['since',
             'movies',
             'one',
             'although',
             'one',
             '?',
             'machine',
             'still',
             "''",
             'also'],
            ['rarity', 'one', 'also', 'narrator', 'its', 'plight', 'full'],
            ['weight',
             "n't",
             'much',
             'tougher',
             'daphne',
             '.',
             'everything',
             '/',
             '.',
             'fred'],
            ['stepped',
             'sprecher',
             'time',
             'much',
             'definition',
             'one',
             '.',
             'another',
             'smaller',
             "'"],
            ['!people!'],
            ['.', '.', '.', 'david', 'jacobson', "'s", 'film', 'time', ';', 'dahmer'],
            ['decided', '!want!'],
            ['stale', '.', "n't", 'one', 'true', 'palma', 'since', 'also', 'first'],
            ['every',
             "'s",
             'extradition',
             'since',
             'another',
             '.',
             'australian',
             'chess',
             'one',
             'accounts'],
            ['!good-humoured!'],
            ["n't", "n't", 'many', 'wo', 'able', 'though'],
            ['walls', 'almost', '!two!'],
            ['even',
             'character',
             'moment',
             '.',
             'much',
             'containing',
             'dense',
             'two',
             'dense'],
            ['!become!'],
            ['flesh', 'nightmare', "'s", 'made', 'one', 'watch', 'came', ',', '.'],
            ['!indicate!'],
            ['!flavor!'],
            ['.', '.', 'colourful', 'intimate', 'heart', 'two', 'another', 'stories'],
            ['deserve', 'manchester', '_', 'conviction', 'one', 'its', 'own'],
            ['even',
             'of',
             'time',
             'older',
             'since',
             'stevenson',
             'would',
             'one',
             'would',
             '.'],
            ["!'re!"],
            ['leave',
             'even',
             'another',
             'less',
             'bourne',
             '?',
             'two',
             'another',
             'traditional',
             'action'],
            ['oliver',
             'neither',
             'novel',
             'inept',
             'schools',
             'still',
             ',',
             'might',
             'parker',
             'productions'],
            ['on', 'its', 'decorum', 'of', 'depictions', 'own'],
            ['much', 'instead', "'s", 'one', 'also', 'jerry', 'try', 'also', 'since'],
            ['of',
             'for',
             'although',
             '.',
             'filmgoers',
             'working',
             'one',
             'even',
             'first'],
            ['!since!'],
            ['!movie!'],
            ['time', 'queen', 'one', 'of', '.', 'part', "'80s", 'its'],
            ['actress',
             'trips',
             'first',
             'could',
             'less',
             'u.s.',
             'also',
             'since',
             'since',
             'gibson'],
            ['first',
             'also',
             'script',
             'syrupy',
             'of',
             'part',
             'even',
             'yet',
             'of',
             'became'],
            ['!anymore!'],
            ['of', '.', 'could', '.', ',', 'full', 'also', 'fast', 'another'],
            ['!also!'],
            ['!still!'],
            ['caricatures', '!cartoons!'],
            ['of',
             'mesh',
             '-',
             'old-world',
             'another',
             'incarnated',
             'films',
             'effusion',
             'another',
             'of'],
            ['one',
             'would',
             'of',
             'jones',
             'another',
             'nothing',
             'charisma',
             'offers',
             'forms'],
            ['conspicuously',
             'plundered',
             'balsamic',
             'short',
             'work',
             'also',
             'different',
             'thorn',
             'of'],
            ['also', 'time', 'one', 'could', 'also', 'arc', 'reality'],
            ['serving', 'serve', 'back', '!would!'],
            ['whether', 'fact', 'for', 'miss', 'however', '.', "!n't!"],
            ['!little!'],
            ['would',
             'although',
             'supernatural',
             'buttercup',
             'cannot',
             'powers',
             'one',
             'also',
             'fact',
             'flimsy'],
            ['even',
             'wild',
             'thornberrys',
             'another',
             'hollywood',
             'another',
             'still',
             'one'],
            ['also', 'provided', 'companies', 'even', 'by'],
            ['leave', 'also', '.', 'another', 'done', "'s", 'highly', 'able'],
            ['pedestrian', 'something', '!regularly!'],
            ['another', 'also', '!still!'],
            ['engrossing',
             'affairs',
             'heavier',
             'convictions',
             'wife',
             'whose',
             'macdowell',
             'help',
             'brings'],
            ['since', 'round-robin', '!less!'],
            ['!would!'],
            ["!'m!"],
            ['also', 'directed', 'however', '.', 'one', 'one', 'one'],
            ['!everyone!'],
            ['films',
             'would',
             'time',
             'cinemas',
             'time',
             'baseball',
             'weeks',
             'of',
             'hitting'],
            ['offbeat',
             'one',
             'help',
             'also',
             'spring',
             '.',
             'arnold',
             'still',
             'his',
             'gerald'],
            ['of',
             'visible',
             'either',
             'efforts',
             'especially',
             'complete',
             'originality',
             '.'],
            ['spectacle', 'add', '``', '.', 'least', 'scenery', 'would', 'also', "'"],
            ['tales', 'seem', 'one', 'one', 'would', 'also', 'others', 'whose', 'live'],
            ['even',
             'one',
             'huge',
             'stories',
             'hits',
             'also',
             'miss',
             'also',
             'takes',
             'since'],
            ['underdeveloped',
             'felt',
             'also',
             ',',
             'something',
             'of',
             "n't",
             'little',
             "!n't!"],
            ['movie', '.', 'one', 'even', 'deep', 'one', 'one', 'one', 'one'],
            ['!taken!'],
            ['pr', 'pure', "'s", 'hoopla', 'also', 'however', '.', '.', '.', '.'],
            ['!try!'],
            ['!lad!'],
            ['himself', 'pounds', 'also', 'from', ',', 'also', 'his', 'role', 'on'],
            ['from', 'of', 'time', 'one', 'walt', 'splash', 'pastel', '.', 'colours'],
            ['made',
             ',',
             '.',
             'another',
             'characters',
             'way',
             'researchers',
             'intense',
             'brooding',
             'proves'],
            ['shortsighted',
             'vibes',
             'radio',
             'of',
             '.',
             'even',
             'another',
             'amalgam',
             'news',
             'another'],
            ['documentary',
             'pinocchio',
             'stunningly',
             'lacked',
             'totally',
             'another',
             'wit',
             'also'],
            ['!salton!'],
            ['chateau',
             'first',
             'also',
             'time',
             'between',
             'differences',
             'gauls',
             'probe',
             'one'],
            ['!away!'],
            ['!one!'],
            ['away', 'give', ',', 'one', 'one', 'cannot', 'theatre'],
            ['come',
             'another',
             'boss',
             'fleetingly',
             'perry',
             'by',
             'thing',
             'cedric',
             'also'],
            ['from',
             'one',
             'khouri',
             'filmgoing',
             'though',
             'actors',
             'whose',
             'normally',
             'try',
             'sort'],
            ['parade',
             'must',
             'talk',
             'linux',
             'gibberish',
             'causes',
             'bit',
             'advance',
             'technical'],
            ['!,!'],
            ['one',
             'less',
             'three',
             'however',
             'wo',
             'conflicted',
             ':',
             'even',
             'character'],
            ['monotonous',
             'bring',
             'gimmick',
             'time',
             'another',
             'one',
             'filmed',
             'of',
             'noteworthy'],
            ['still',
             'own',
             'could',
             'event',
             'passes',
             'even',
             'enough',
             'first',
             'two',
             'another'],
            ['.', "'m", 'also', 'serious', 'by', 'since', 'by'],
            ['get', ',', 'junk', '!would!'],
            ["n't",
             'deepen',
             'ideas',
             'come',
             'also',
             'one',
             'complex',
             'also',
             'still',
             'others'],
            ['first',
             'nearly',
             'also',
             'nation',
             'runner-up',
             'stars',
             '_',
             'above',
             'featured',
             '!hardly!'],
            ['repellent',
             'downright',
             'would',
             'unfunny',
             'also',
             'even',
             "n't",
             'however',
             '.',
             '.'],
            ['try', 'work', '!wanted!'],
            ['notion', 'last', "!n't!"],
            ['unforgivably',
             'tooth',
             'continue',
             'turns',
             'take',
             'second',
             'expected',
             'sugar'],
            ['cliched', 'his', 'rarely', 'giving', 'also', 'levels', 'either'],
            ['character', 'stages', 'stages', 'on', '.', 'leads', 'his', 'film', '.'],
            ['tales', 'also', 'also', 'of', 'also', 'one', 'even', '.'],
            ['even', 'one', 'tosca', 'also', 'opera', 'time', 'films'],
            ['even',
             'one',
             'documentary',
             '.',
             'another',
             '.',
             'unforgettable',
             'quiet',
             'one'],
            ['watch', 'children', 'one', 'much', ',', 'since', 'one'],
            ['!12!'],
            ['your', 'stanford', 'of', 'stands', 'larceny', ',', '!everyone!'],
            [',', 'filmmakers', 'one', 'christian', 'first', 'make', '(', 'movie'],
            ['even',
             'hun',
             'one',
             'much',
             'of',
             'equal',
             'enormous',
             'amount',
             'of',
             'one'],
            ['choice', 'movie', 'least', "'s", "'", 'of', 'week', 'another'],
            ['little',
             'something',
             'igloo',
             'preparations',
             'on',
             'also',
             'one',
             '.',
             'yet'],
            ['since',
             'even',
             "n't",
             'actress',
             'first-time',
             'another',
             'its',
             'director',
             'one'],
            ['add', 'anything', 'genre', 'would', 'sort', "'s", ',', 'way', 'of', 'of'],
            ['!feel!'],
            ['pompous',
             'appropriately',
             'of',
             'weight',
             'also',
             'portentous',
             'taken',
             'of',
             'also',
             'much'],
            ['even',
             'one',
             'also',
             'one',
             'taken',
             'much',
             'reconsideration',
             '.',
             'even'],
            ['much', 'one', 'even', 'marquis', 'la', 'sade', 'taken', 'fact', '?'],
            ['also', 'time', 'rarely', 'cannot', '.', '.', 'one'],
            ['stories',
             'time',
             'of',
             'became',
             'however',
             '.',
             '.',
             'didactic',
             'jose',
             'director'],
            ['also',
             'put',
             'one',
             'episode',
             'back',
             'remember',
             'made',
             'partway',
             'saccharine'],
            ['!even!'],
            ['uses',
             'systems',
             'hefty',
             'one',
             'would',
             'scoring',
             "'s",
             'rousing',
             'either',
             'one'],
            ['never',
             'could',
             'fingered',
             'freddy',
             ',',
             'released',
             'another',
             'able',
             'major'],
            ['put',
             'time',
             'else',
             'know',
             'blow',
             "'d",
             'one',
             'time',
             'hollywood',
             'time'],
            ['!last!'],
            ['tell', '``', "''", 'time', 'come', 'need'],
            ['still', 'since', '!quite!'],
            ['haphazard',
             'stir',
             'thing',
             'silly',
             'writers',
             "n't",
             'must',
             'attain',
             'pot',
             'yet'],
            ['familiar', '!even!'],
            ['implodes', 'since', 'at', 'also', 'even', 'effects', 'of'],
            ['.', 'adult', 'johnson', '.', 'of', '2013', 'least', "'s"],
            ['!let!'],
            ['meditation', 'on', ',', '.', 'another', 'one', 'family', 'without'],
            ['palpable',
             'viewer',
             'could',
             'start',
             'mystery',
             'of',
             "'s",
             'by',
             'first'],
            ['first',
             'since',
             'suspense',
             'for',
             'thought',
             'part',
             'obama',
             '!seventh!'],
            ['one',
             'tour',
             'humorous',
             '.',
             'amazingly',
             'still',
             "'s",
             'another',
             'military',
             'subtly'],
            ['time',
             'of',
             'understanding',
             'another',
             'sarcastic',
             'one',
             'director',
             'niccol',
             'idiosyncrasies'],
            ['later',
             'plugged',
             'leguizamo',
             'characters',
             'since',
             'another',
             'time',
             '!never!'],
            ['colourful',
             'bigger',
             'at',
             'wo',
             '.',
             'kaleidoscope',
             'staying',
             'of',
             'character',
             'another'],
            ['profundity',
             'also',
             'tiresomely',
             'indicating',
             'itself',
             ',',
             'even',
             'sure',
             'one'],
            ['moment', "'d", 'chris', 'everyone', 'routine', 'random', 'one'],
            ['laborious',
             'wacky',
             '.',
             'another',
             'eventually',
             'would-be',
             'also',
             'sexual'],
            ['one', '!away!'],
            ['even',
             'documentary',
             'either',
             'part',
             'one',
             'one',
             'however',
             'fontaine',
             'still',
             'four'],
            ['since',
             'wallow',
             'depths',
             'in-your-face',
             'sang',
             'by',
             'others',
             'whose',
             'also'],
            ['picture', 'another', '.', 'little', '.', 'even', 'well-made', 'one'],
            ['child', 'one', 'part', 'at', 'basis', 'first', ',', 'of', 'first'],
            ['!still!'],
            ['take',
             'since',
             'never',
             'his',
             'superficially',
             'knows',
             'way',
             'michael',
             'director'],
            ['!could!'],
            ['!one!'],
            ['!,!'],
            ['banal', 'vulgar', 'yet', 'also', 'time', ',', 'one', ',', ',', ','],
            ['job', 'mostly', '!gotten!'],
            ['!,!'],
            ['trick',
             'even',
             'languages',
             "''",
             'since',
             'later',
             'detective',
             '.',
             ';',
             "'s"],
            ['whiny',
             'downer',
             'commentary',
             'nearly',
             'many',
             'one',
             'one',
             'one',
             'one'],
            ['among', '_', 'door', 'reason', "!n't!"],
            ['character', ',', 'also', 'flick', 'also', "'s", 'two'],
            ['also',
             'word',
             'fuelling',
             'part',
             'two',
             'worries',
             'another',
             'one',
             'acts'],
            ['!thing!'],
            [',',
             'your',
             'stomach',
             'part',
             'movies',
             'knot',
             'forces',
             'felt',
             'accumulated'],
            ['enough', 'at', ',', 'scene', 'listeners', "n't", 'able', 'their', 'retain'],
            ['even',
             'gender',
             'likely',
             'another',
             'try',
             'alienate',
             'also',
             'also',
             'makes'],
            ['considered',
             'sustain',
             'make',
             'picture',
             'yet',
             "'s",
             '.',
             'sprawling',
             'another']]

def get_embedding_words():
    # Replace this function with all the embedding words
    return [["!embedding!"],["words"]]

def get_attention_words():
    # Replace this function with all the attention words
    return [["!attention!"],["words"]]

def get_words():
    return [get_rnn_words(), get_embedding_words(), get_attention_words()]


# Remove the ! from the words
def flatten(x):
    if isinstance(x, list):
        return [a for i in x for a in flatten(i)]
    else:
        return [x]

def words_in_glove(word: str):
  return word != None and word != "''" and word != ""



def get_flatten_words():
    rnn_words, embedding_words, attention_words = get_words()
    return filter_words(rnn_words), filter_words(embedding_words), filter_words(attention_words)


def filter_words(words: list):
    flatten_words = flatten(words)
    print(len(words))
    flatten_words2 = list(filter(words_in_glove, [w.replace("!", "") for w in flatten_words]))
    print(len(flatten_words2))
    return list(set(flatten_words2))


def filter_only_successfull_cases(word: str):
    return word.__contains__("!")


def get_only_successful_words():
    rnn_words, embedding_words, attention_words = get_words()
    print("got words", len(rnn_words), len(embedding_words), len(attention_words))
    return filter_successful_words(rnn_words), filter_successful_words(embedding_words), filter_successful_words(attention_words)


def filter_successful_words(words: list):
    flatten_words = flatten(words)
    flatten_words2 = list(filter(filter_only_successfull_cases, flatten_words))
    flatten_words2 = [w.replace("!", "") for w in flatten_words2]
    flatten_words2 = list(filter(words_in_glove, [w.replace("!", "") for w in flatten_words2]))

    print(len(flatten_words2))
    return list(set(flatten_words2))


# create run main
if __name__ == '__main__':
    print(get_only_successful_words())